CAFF-55 tuning navigation parameters (minheights, local costmap size)
UTRA-ART/Caffeine pull request #58
Opened 2021-03-13 19:06 UTC by MarcM0

Changing values, looking at obstacles in rviz, until numbers were fine tuned

2021-03-13 21:13 UTC, 1999michael requested changes
End of file needs empty lines, otherwise it looks good to me

2021-03-13 21:13 UTC, 1999michael commented on nav/nav_stack/config/costmap_common_params.yaml
> +}
Add newline to end of file

2021-03-13 21:13 UTC, 1999michael commented on nav/nav_stack/config/local_costmap_params.yaml
> +resolution: 0.05
Add newline to end of file

2021-03-13 22:01 UTC, MarcM0 commented on nav/nav_stack/config/costmap_common_params.yaml
> +}
added

2021-03-13 22:02 UTC, MarcM0 commented on nav/nav_stack/config/local_costmap_params.yaml
> +resolution: 0.05
added

2021-03-20 16:08 UTC, 1999michael approved these changes
Looks good to me

2021-03-20 17:28 UTC, erickmu1 approved these changes

2021-03-20 17:33 UTC, merged